# Project: Proyecto1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o funcion.o $(RES)
LINKOBJ  = main.o funcion.o $(RES)
LIBS =  -L"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/lib" -g  
INCS =  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include" 
CXXINCS =  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include/c++/3.4.2"  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include" 
BIN  = Ejercicio34.exe
CXXFLAGS = $(CXXINCS)   -g
CFLAGS = $(INCS)   -g
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Ejercicio34.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "Ejercicio34.exe" $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

funcion.o: funcion.c
	$(CC) -c funcion.c -o funcion.o $(CFLAGS)
