# Project: Proyecto4
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = ejercicio9.o $(RES)
LINKOBJ  = ejercicio9.o $(RES)
LIBS =  -L"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/lib" -g  
INCS =  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include" 
CXXINCS =  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include/c++/3.4.2"  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include" 
BIN  = Proyecto9.exe
CXXFLAGS = $(CXXINCS)   -g
CFLAGS = $(INCS)   -g
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Proyecto9.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "Proyecto9.exe" $(LIBS)

ejercicio9.o: ejercicio9.c
	$(CC) -c ejercicio9.c -o ejercicio9.o $(CFLAGS)
