# Project: Proyecto2
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = Ejercicio36(vectores).o $(RES)
LINKOBJ  = Ejercicio36(vectores).o $(RES)
LIBS =  -L"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/lib" -g  
INCS =  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include" 
CXXINCS =  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include/c++/3.4.2"  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include" 
BIN  = Ejercicio36(Vectores).exe
CXXFLAGS = $(CXXINCS)   -g
CFLAGS = $(INCS)   -g
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Ejercicio36(Vectores).exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "Ejercicio36(Vectores).exe" $(LIBS)

Ejercicio36(vectores).o: Ejercicio36(vectores).c
	$(CC) -c Ejercicio36(vectores).c -o Ejercicio36(vectores).o $(CFLAGS)
