# Project: Proyecto2
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = Ejercicio17.o $(RES)
LINKOBJ  = Ejercicio17.o $(RES)
LIBS =  -L"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/lib" -g  
INCS =  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include" 
CXXINCS =  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include/c++/3.4.2"  -I"C:/Users/Usuario/Documents/Facundo/Dev-Cpp/include" 
BIN  = Proyecto17.exe
CXXFLAGS = $(CXXINCS)   -g
CFLAGS = $(INCS)   -g
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Proyecto17.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "Proyecto17.exe" $(LIBS)

Ejercicio17.o: Ejercicio17.c
	$(CC) -c Ejercicio17.c -o Ejercicio17.o $(CFLAGS)
